services:
  app:
    image: harbor.revengine.dailymaverick.co.za/revengine/vector-engine:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8002:8001
    depends_on:
      - qdrant
      - redis
      - ollama
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_URL=http://qdrant:6333
      - REDIS_HOST=redis
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./articles:/app/articles
      - ./src:/app/src
      - ./tests:/app/tests
    deploy:
      mode: replicated
      replicas: 1

  test:
    image: harbor.revengine.dailymaverick.co.za/revengine/vector-engine:latest
    depends_on:
      - qdrant
      - redis
      - ollama
      - mongodb
      - mock-api
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_URL=http://qdrant:6333
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OLLAMA_URL=http://ollama:11434
      - JXP_API_URL=http://mock-api:3000
      - JXP_API_KEY=test_key
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongodb:27017/vectorizer
    volumes:
      - ./articles:/app/articles
      - ./src:/app/src
      - ./tests:/app/tests
    command: npm test

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    deploy:
      mode: global
    ports:
      - "127.0.0.1:6335:6333"

  redis:
    image: redis:latest
    deploy:
      mode: global

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    deploy:
      mode: global
    volumes:
      - ./models:/.ollama/models
    privileged: true
  
  mongodb:
    image: mongo:latest
    deploy:
      mode: global
      replicas: 1
    volumes:
      - mongodb_data:/data/db
      - ./mongodb_dump:/data/mongodb_dump
    ports:
      - "127.0.0.1:27018:27017"

  mock-api:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./tests/mocks:/app
    command: >
      sh -c "npm install express cors --no-save && 
             node mock-api-server.js"
    ports:
      - "127.0.0.1:3010:3000"

volumes:
  qdrant_data:
  mongodb_data:
