services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - qdrant
      - redis
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_URL=http://qdrant:6333
      - REDIS_HOST=redis
    volumes:
      - ./articles:/app/articles
      - ./src:/app/src

  qdrant:
    image: qdrant/qdrant:latest
    # ports:
    #   - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:latest
    # ports:
    #   - "6379:6379"

volumes:
  qdrant_data:
