services:
  app:
    image: harbor.revengine.dailymaverick.co.za/revengine/vector-engine:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8001:8001
    depends_on:
      - qdrant
      - redis
      - ollama
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_URL=http://qdrant:6333
      - REDIS_HOST=redis
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./articles:/app/articles
      - ./src:/app/src
      - ./tests:/app/tests
    deploy:
      mode: replicated
      replicas: 1

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    deploy:
      mode: global
    ports:
      - "127.0.0.1:6335:6333"

  redis:
    image: redis:latest
    deploy:
      mode: global

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    deploy:
      mode: global
    volumes:
      - ./models:/.ollama/models
    privileged: true
  
  mongodb:
    image: mongo:latest
    deploy:
      mode: global
      replicas: 1
    volumes:
      - mongodb_data:/data/db
      - ./mongodb_dump:/data/mongodb_dump
    ports:
      - "127.0.0.1:27018:27017"

volumes:
  qdrant_data:
  mongodb_data:
