services:
  app:
    image: jasony/vector-engine:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8001:8001
    depends_on:
      - qdrant
      - redis
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_URL=http://qdrant:6333
      - REDIS_HOST=redis
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./articles:/app/articles
      - ./src:/app/src
    deploy:
      mode: replicated
      replicas: 1

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    deploy:
      mode: global

  redis:
    image: redis:latest
    deploy:
      mode: global

  ollama:
    # image: ollama/ollama:latest
    build:
      context: ./ollama
      dockerfile: Dockerfile
    # ports:
    #   - 8000:8000
    deploy:
      mode: global
    volumes:
      - ./models:/.ollama/models
    # command: 
    #   - /bin/ollama pull all-minilm
    #   - ollama serve
      
volumes:
  qdrant_data:
